# spring:
#   datasource:
#     driverClassName: org.postgresql.Driver
#     url: jdbc:postgresql://localhost:5432/postgres
#     username: postgres
#     password: 
#   jpa:
#     hibernate:
#       #create-drop is for initial testing since it will recreate your tables over again
#       #update all it does is update your tables and it will not recreate (persistent for production)
#       #validate will just validate that schema should be the same
#       ddl-auto: create-drop
#     show-sql: true
#     properties:
#       dialect: org.hibernate.dialect.PostgreSQLDialect
# server:
#   port: 